Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using NiceAdmin.Models;
using System.Data.SqlClient;
using System.Data;
using System.Collections.Specialized;
using OfficeOpenXml;

namespace NiceAdmin.Controllers
{
    public class BillController : Controller
    {
        private IConfiguration configuration;

        public BillController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult Bills()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection sqlConnection = new SqlConnection(connectionString);
            sqlConnection.Open();
            SqlCommand sqlCommand = sqlConnection.CreateCommand();
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.CommandText = "PR_Bills_SelectAll";
            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return View(dataTable);
        }

        public IActionResult BillDelete(int BillID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_Bills_DeleteByPK";
                sqlCommand.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID;
                sqlCommand.ExecuteNonQuery();
                return RedirectToAction("Bills");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString);
                return RedirectToAction("Bills");
            }
        }

        public IActionResult BillSave(BillModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.BillID == 0)
                {
                    command.CommandText = "PR_Bills_Insert";
                }
                else
                {
                    command.CommandText = "PR_Bills_UpdateByPK";
                    command.Parameters.Add("@BillID", SqlDbType.Int).Value = model.BillID;
                }
                command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = model.BillNumber;
                command.Parameters.Add("@BillDate", SqlDbType.Date).Value = model.BillDate;
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = model.OrderID;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = model.TotalAmount;
                command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = model.Discount;
                command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = model.NetAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserID;
                command.ExecuteNonQuery();
                TempData["SuccessMessage"] = model.BillID == 0 ? "Bill added successfully!" : "Bill updated successfully!";
                return RedirectToAction("Bills");
            }

            return View("BillsForm", model);
        }
        public IActionResult BillsForm(int? BillID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            SqlConnection sqlConnection1 = new SqlConnection(connectionString);
            sqlConnection1.Open();
            SqlCommand command1 = sqlConnection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }

            ViewBag.Users = userList;

            SqlConnection sqlConnection2 = new SqlConnection(connectionString);
            sqlConnection2.Open();
            SqlCommand command2 = sqlConnection1.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_Orders_DropDown";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable2.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderDropDownModel.OrderCode = data["OrderCode"].ToString();
                orderList.Add(orderDropDownModel);
            }

            ViewBag.Orders = orderList;

            BillModel billModel = new BillModel();
            if (BillID.HasValue)
            {
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_Bills_SelectByPK";
                command.Parameters.AddWithValue("@BillID", BillID);
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                foreach (DataRow dataRow in table.Rows)
                {
                    billModel.BillID = Convert.ToInt32(dataRow["OrderID"]);
                    billModel.BillNumber = @dataRow["BillNumber"].ToString();
                    billModel.BillDate = Convert.ToDateTime(@dataRow["BillDate"]);
                    billModel.OrderID = Convert.ToInt32(@dataRow["OrderID"]);
                    billModel.TotalAmount = Convert.ToDecimal(@dataRow["TotalAmount"]);
                    billModel.Discount = Convert.ToDecimal(@dataRow["Discount"]);
                    billModel.NetAmount = Convert.ToDecimal(@dataRow["NetAmount"]);
                    billModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
                }

                ViewData["Title"] = "Edit Bill";
            }
            else
            {
                ViewData["Title"] = "Add Bill";
            }
            return View("BillsForm", billModel);
        }

        public IActionResult ExportToExcel()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (var sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                using (var sqlCommand = sqlConnection.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_Bills_SelectAll";
                    using (var sqlDataReader = sqlCommand.ExecuteReader())
                    {
                        var dataTable = new DataTable();
                        dataTable.Load(sqlDataReader);

                        using (var package = new ExcelPackage())
                        {
                            var worksheet = package.Workbook.Worksheets.Add("Users");
                            worksheet.Cells["A1"].LoadFromDataTable(dataTable, true);

                            var stream = new MemoryStream();
                            package.SaveAs(stream);
                            stream.Position = 0;

                            var fileName = "Bills.xlsx";
                            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                        }
                    }
                }
            }
        }
    }
}

Controllers/EmailController.cs
using Microsoft.AspNetCore.Mvc;
using NiceAdmin.Services;
using System.Threading.Tasks;

namespace NiceAdmin.Controllers
{
    public class EmailController : Controller
    {
        private readonly IEmailService _emailService;

        public EmailController(IEmailService emailService)
        {
            _emailService = emailService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> SendEmail()
        { 

            await _emailService.SendEmailAsync("ritesh.lakhani1507@gmail.com","Normal Check","HII Message Comes From Ritesh");

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Pages / Coffee Shope</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
   <!-- ======= Header ======= -->
            <header id="header" class="header fixed-top d-flex align-items-center">
                <div class="d-flex align-items-center justify-content-between">
                    <a href="@Url.Action("Index", "Home")" class="logo d-flex align-items-center">
                 <img src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/coffee-shop-logos-design-template-cda8575e146cc5ba17cd3c1a24d65ba1_screen.jpg?ts=1638177256" alt="Coffee Shop Logo" style="max-height: 50px; width: auto;">
                        <span class="d-none d-lg-block">Coffee Shop</span>
                    </a>
                    <i class="bi bi-list toggle-sidebar-btn"></i>
                </div><!-- End Logo -->

                <nav class="header-nav ms-auto">
                    <ul class="d-flex align-items-center">
                        <!-- Profile dropdown -->
                        <li class="nav-item dropdown pe-3">
                            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="~/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                                <span class="d-none d-md-block dropdown-toggle ps-2">Het Savani</span>
                            </a>
                            <!-- Dropdown menu -->
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile" aria-labelledby="profileDropdown">
                                <li>
                                    <form asp-controller="User" asp-action="Logout" method="post">
                                        <button type="submit" class="dropdown-item d-flex align-items-center">
                                            <i class="bi bi-box-arrow-right"></i>
                                            <span>Log Out</span>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </li><!-- End Profile Nav -->
                    </ul>
                </nav><!-- End Icons Navigation -->
            </header><!-- End Header -->


    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
       <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="index">
                    <i class="bi bi-home"></i><span>Dashboard</span>
                </a>
            </li>

           <li class="nav-item">
                <a class="nav-link" asp-controller="User" asp-action="User">
                    <i class="bi bi-person"></i><span>User</span>
                </a>
           </li><!-- End User Nav -->


            <li class="nav-item">
                <a class="nav-link" asp-controller="Product" asp-action="Product">
                    <i class="bi bi-box"></i><span>Product</span>
                </a>
            </li><!-- End Product Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="Customer" asp-action="Customer">
                    <i class="bi bi-people"></i><span>Customer</span>
                </a>
            </li><!-- End Customer Nav -->

            <li class="nav-item">
                 <a class="nav-link" asp-controller="Order" asp-action="Order">
                    <i class="bi bi-receipt"></i><span>Order</span>
                </a>
            </li><!-- End Order Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="OrderDetail" asp-action="OrderDetail">
                    <i class="bi bi-card-list"></i><span>Order Detail</span>
                </a>
            </li><!-- End OrderDetail Nav -->

            <li class="nav-item">
                 <a class="nav-link" asp-controller="Bill" asp-action="Bills">
                    <i class="bi bi-receipt-cutoff"></i><span>Bill</span>
                </a>
            </li><!-- End Bills Nav -->

            <li class="nav-item">
                 <a class="nav-link" asp-controller="Email" asp-action="Index">
                    <i class="bi bi-envelope"></i><span>Email</span>
                </a>
            </li><!-- End Email Nav -->
        </ul>
    </aside><!-- End Sidebar-->




        <main role="main" class="pb-3">
        @RenderBody()
        </main>


     <!-- ======= Footer ======= -->
                <footer id="footer" class="footer">
                    <div class="copyright">
                        &copy; Copyright <strong><span>Het Savani</span></strong>. All Rights Reserved
                    </div>
                    <div class="credits">
                        <!-- All the links in the footer should remain intact. -->
                        <!-- You can delete the links only if you purchased the pro version. -->
                        <!-- Licensing information: https://bootstrapmade.com/license/ -->
                        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                        Designed by <a href="https://bootstrapmade.com/">DU</a>
                    </div>
                </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


    <!-- Vendor JS Files -->
    <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/chart.js/chart.umd.js"></script>
    <script src="~/vendor/echarts/echarts.min.js"></script>
    <script src="~/vendor/quill/quill.js"></script>
    <script src="~/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>
    


    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    <!-- Include jQuery and Bootstrap JS -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Pages / Login - CoffeeShop</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="https://th.bing.com/th/id/OIP.3l72hn0LshdLgG5RBQD91QAAAA?rs=1&pid=ImgDetMain" rel="icon" type="image/png">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
    @RenderBody()
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/chart.js/chart.umd.js"></script>
    <script src="~/vendor/echarts/echarts.min.js"></script>
    <script src="~/vendor/quill/quill.min.js"></script>
    <script src="~/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>